name: KTools Config
description: 'Show Environment config of a ktools instance'
inputs:
  environment:
    description: Environment 
    required: true
  cleanup:
    description: |
      Deletes the log subscription after executing the command. Set it to false if you plan to run other ktools commands in the same pipeline.
    default: 'true'
    required: false
  subcommand:
    default: config
    description: action subcommand
    required: false
  operation:
    default: show
    description: operation of subcommand
    required: false
    
    
runs:
  using: 'node16'
  main: '../run.js'
