name: KTools Refresh
description: 'Update a kt installation'
inputs:
  environment:
    description: Environment 
    required: true
  cleanup:
    description: |
      Deletes the log subscription after executing the command. Set it to false if you plan to run other ktools commands in the same pipeline.
    default: 'true'
    required: false
  subcommand:
    default: refresh
    description: action subcommand
    required: false
  operation:
    default: refresh
    description: operation of subcommand
    required: false
    
    
runs:
  using: 'node16'
  main: '../run.js'
