name: KTools Service Status
description: |
  Show the status of Kentik Services
inputs:
  environment:
    description: Environment 
    required: true
  service_group:
    description: Name of the service
    required: true
  cleanup:
    description: Deletes the log subscription after executing the command. Set it to false if you plan to run other ktools commands in the same pipeline.
    default: 'true'
    required: false
  subcommand:
    default: deploy
    description: action subcommand [ignore this input]
    required: false
  operation:
    default: status
    description: operation of subcommand [ignore this input]
    required: false
    
    
runs:
  using: 'node16'
  main: '../../run.js'
