name: 'ktools deploy push'
description: 'Deploy Kentik services using Github Actions'
inputs:
  environment:
    description: Environment 
    required: true
  service_group:
    description: Name of the service
    required: true
  branch:
    description: 'Deploy service using image built from this branch. Append the build number to deploy a specific version. Example: `master.10`'
    default: master
    required: false
  cleanup:
    description: |
      The log subscription won't be deleted if true. Set to `true` if you plan to run more kt commands in the pipeline. Set to false in the last command
    default: 'true'
    required: false
  subcommand:
    default: deploy
    description: action subcommand
    required: false
  operation:
    default: push
    description: operation of subcommand
    required: false
    
    
runs:
  using: 'node16'
  main: '../../run.js'
