name: Build using earthly

on:
  workflow_call:
    inputs:
      earthly_target:
        required: true
        type: string
      earthly_multi_target:
        required: false
        type: string
      build_multi:
        required: false
        type: boolean
        default: false

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    # Allow the job to fetch a GitHub ID token
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Run Earthly
        uses: kentik/github-workflows/earthly@main
        with:
          github_token: ${{ secrets.KENTIK_ALL_GITHUB_TOKEN }}
          earthly_target: ${{ inputs.earthly_target }}
          earthly_multi_target: ${{ inputs.earthly_multi_target }}
          build_multi: ${{ inputs.build_multi }}