name: Deploy with ktools

on:
  workflow_call:
    inputs:
      service_group:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: ${{ github.ref_name }}
      autodeploy_branches:
        required: false
        type: string
        default: '["master", "pipes"]'


jobs:
  wait_for_build:
    name: Wait for Build
    runs-on: ubuntu-latest
    if: >-
      (
        contains(github.event.head_commit.message, '#deployour1') ||
        contains(github.event.head_commit.message, '#deploy') ||
        contains(toJSON(inputs.autodeploy_branches), github.ref_name)
      ) && 
      ! contains(github.event.head_commit.message, '#nodeploy')
    steps:

      - name: Wait for Build
        uses: bernardovale/action-wait-for-check@allowed-status
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Jenkins
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 5
          timeoutSeconds: 1800
          allowedStatus: success

  deploy:
    name: Deploy to Staging (our1)
    needs: wait_for_build

    runs-on: ubuntu-latest
    if: >-
      contains(github.event.head_commit.message, '#deployour1') ||
      contains(github.event.head_commit.message, '#deploy') ||
      github.ref_name == 'master'

    # Allow the job to fetch a GitHub ID token
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Configure Credentials
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/70880649570/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "svc-github-ktools-action@kentik-continuous-delivery.iam.gserviceaccount.com"

      - name: Show Current Status
        uses: kentik/github-workflows/ktools/deploy/status@kt
        with:
          service_group: ${{ inputs.service_group }}
          environment: our1
          cleanup: false

      - name: Deploy Service
        uses: kentik/github-workflows/ktools/deploy/push@kt
        with:
          service_group: ${{ inputs.service_group }}
          environment: our1
          branch: ${{ inputs.branch }}

        
      