name: Deploy with ktools

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      service_group:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: master



jobs:
  wait_for_build:
    name: Wait for Build
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Build
        uses: lewagon/wait-on-check-action@v1.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          check-name: Jenkins
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          allowed-conclusions: success
        if: ${{ contains(github.event.head_commit.message, '#deployour1') ||  github.ref_name == 'master' }}

  deploy:
    name: Deploy to Staging (our1)
    needs: wait_for_build

    runs-on: ubuntu-latest

    # Allow the job to fetch a GitHub ID token
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Configure Credentials
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/70880649570/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "svc-github-ktools-action@kentik-continuous-delivery.iam.gserviceaccount.com"

      - name: Show Current Status
        uses: ../../ktools/deploy/status
        with:
          service_group: ${{ inputs.service_group }}
          environment: our1
        if: ${{ contains(github.event.head_commit.message, '#deployour1') ||  github.ref_name == 'master' }}
        
