name: Deploy with ktools

on:
  workflow_call:
    inputs:
      service_group:
        required: true
        type: string
      branch:
        required: false
        type: string
        default: master



jobs:
  wait_for_build:
    name: Wait for Build
    runs-on: ubuntu-latest
    steps:

      - name: Wait for Build
        uses: bernardovale/action-wait-for-check@allowed
        id: wait-for-build
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Jenkins
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          intervalSeconds: 2
          timeoutSeconds: 1800
          allowedStatus: failure
        if: ${{ contains(github.event.head_commit.message, '#deployour1') ||  github.ref_name == 'master' }}

      # - name: Wait for Build
      #   uses: lewagon/wait-on-check-action@v1.0.0
      #   with:
      #     allowed-conclusions: success
      #   if: ${{ contains(github.event.head_commit.message, '#deployour1') ||  github.ref_name == 'master' }}

  deploy:
    name: Deploy to Staging (our1)
    needs: wait_for_build

    runs-on: ubuntu-latest

    # Allow the job to fetch a GitHub ID token
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Configure Credentials
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/70880649570/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "svc-github-ktools-action@kentik-continuous-delivery.iam.gserviceaccount.com"
        if: ${{ contains(github.event.head_commit.message, '#deployour1') ||  github.ref_name == 'master' }}

      - name: Show Current Status
        uses: kentik/github-workflows/ktools/deploy/status@kt
        with:
          service_group: ${{ inputs.service_group }}
          environment: our1
        if: ${{ contains(github.event.head_commit.message, '#deployour1') ||  github.ref_name == 'master' }}
        
