name: Deploy to any environment using ktools
on:
  workflow_call:
    inputs:
      service_group:
        required: true
        type: string
      branch:
        required: false
        type: string
      environment:
        required: false
        type: string
        default: our1
      skip-maint:
        description: 'Skip maintenance window (period where Pagerduty alarms are ignored).'
        default: 'false'
        required: false
        type: string
      skip-restart:
        description: 'Skip restart step.'
        default: 'false'
        required: false
        type: string
      emergency-deploy:
        description: "Ignores all constraints/restrictions and proceed with deploy"
        default: 'false'
        required: false
        type: string
      host:
        description: "Deploys only to a comma-separated list of hosts. E.g: c101.our1.kentik.com,c102.our1.kentik.com"
        default: ""
        required: false
        type: string

jobs:

  deploy:
    name: Deploy Service
    
    runs-on: ubuntu-latest

    # Allow the job to fetch a GitHub ID token
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:

      - name: Configure Credentials
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "projects/70880649570/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "svc-github-ktools-action@kentik-continuous-delivery.iam.gserviceaccount.com"

      - name: Show Current Status
        uses: kentik/github-workflows/ktools/deploy/status@id-token
        with:
          service_group: ${{ inputs.service_group }}
          environment: ${{ inputs.environment }}
          cleanup: false

      - name: Deploy Service
        uses: kentik/github-workflows/ktools/deploy/push@id-token
        with:
          service_group: ${{ inputs.service_group }}
          environment: ${{ inputs.environment }}
          branch: ${{ inputs.branch }}
          skip-maint: ${{ inputs.skip-maint }}
          skip-restart: ${{ inputs.skip-restart }}
          emergency-deploy: ${{ inputs.emergency-deploy }}
          host: ${{ inputs.host }}
          cleanup: false

      - name: Show Status
        uses: kentik/github-workflows/ktools/deploy/status@id-token
        with:
          service_group: ${{ inputs.service_group }}
          environment: ${{ inputs.environment }}
